### ISSUE TITLE
Discussion: Improve Handling

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-galaxy-skeleton#11]
### Type of Report

Feature Request /Discussion

### Actual behaviour

Currently a lot of workarounds are needed to get this thing going.
The content is in the root directory of the repo.

### Expected behaviour

A rel-ayouting and some minor work can improve the handling:

```
README.md                  # The description/README.md for this repo
.editorconfig                   # The repo specific .editorconfig
.gitignore                        # The repo specific .gitignore

docs                               # The regular docs will be placed here
tests                               # The tests for this exact repository will be placed here

dist                                 # The skeleton (distributed) will be placed here
   README.md.j2           # Readme.md template for new roles
  .editorconfig                 # The editorconfig for new roles
  .gitignore                      # .gitignore for new repos
  .travis.yml.j2                # Template for new travis files

  docs                             # The docs for new roles will be placed here
  tests                             # Templates for tests
  meta
  tasks
```
I think you got the idea ^^

What do you think about this? From my perspective it will remove the workarounds, allow tests for the repo itself (including a simulated ansible-galaxy init) and can help to keep it up-to-date. One problem will be there. Updating the repository can cause a lot of copy-pasting, because it can happen that multiple files must be touched.

**Comment by daniel-wtd** [comment]
If the above is ok from your side, I'll start the work and open a PR

**Comment by donvipre** [comment]
Not sure about the details, but I like the idea.
Please proceed :)

Daniel S. <notifications@github.com> schrieb am Sa., 3. Feb. 2018, 09:56:

**Comment by daniel-wtd** [comment]
starting with this in https://github.com/while-true-do/ansible-galaxy-skeleton/tree/fb-daniel-wtd
