### ISSUE TITLE
Typo in dist/README.md.j2

### ISSUE THREAD

**Issue by Cinux90** [while-true-do/ansible-galaxy-skeleton#20]
I started to create the KVM role with the skeleton and face an typo in line 40 of [dist/README.md.j2](https://github.com/while-true-do/ansible-galaxy-skeleton/blob/master/dist/README.md.j2#L40)

`You also have to puth the dependencies in the requirements.yml.`

Its only in the comment section of the file, but should be fixed.

**Comment by daniel-wtd** [comment]
this is a duplicate of #18 , can you please have a look and fix the second point, too?
